version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt -t package/
      - cp -r *.py package/
  build:
    commands:
      - cd package
      - zip -r ../app.zip .

artifacts:
  files:
    - app.zip
