
# Data ingestion configuration
data_ingestion:
  raw_data_filename: raw.csv
  ingested_data_filename: ingested_data.csv

# Data validation configuration
data_validation:
  validated_data_filename: validated_data.csv
  missing_report_filename: missing_values_report.yaml
  duplicates_report_filename: duplicates_report.yaml
  drift_report_filename: drift_report.yaml
  validation_report_filename: validation_report.yaml
  categorical_report_filename: categorical_report.yaml

# Data transformation configuration
data_transformation:
  x_train_filename: x_train.npy
  y_train_filename: y_train.npy
  x_val_filename: x_val.npy
  y_val_filename: y_val.npy
  x_test_filename: x_test.npy
  y_test_filename: y_test.npy
  x_preprocessor_filename: x_preprocessor.joblib
  y_preprocessor_filename: y_preprocessor.joblib

# Model trainer configuration
model_trainer:
  model_dir: saved_models
  inference_model_filename: inference_model.joblib
  trained_model_filename: model.joblib
  training_report_filename: training_report.yaml

model_evaluation:
  report_filename: evaluation_report.yaml

# PostGres configuration
postgres_dbhandler:
  input_data_dir: student_data
  input_data_filename: stud.csv
  dbname: student_performance_db
  table_name: student_scores

s3_handler:
  s3_bucket: studentperformance-dev-artifacts
  s3_inference_model_prefix: inference_model
  s3_artifacts_prefix: artifacts
  
data_backup:
  s3_enabled: true
  local_enabled: false

