# Parameters for drift detection during data validation
validation_params:
  drift_detection:
    enabled: true
    method: ks_test
    p_value_threshold: 0.05

  schema_check:
    enabled: true
    method: hash

transformation_params:
  data_split:
    train_size: 0.6
    val_size: 0.2
    test_size: 0.2
    random_state: 42
    stratify: false

  steps:
    x:
      - encoding
    y:
      - column_math

  methods:
    x:
      column_operation:
        method: remove_col
        columns:
          - id
      encoding:
        method: one_hot
        handle_unknown: ignore
        columns:
          - gender
          - race_ethnicity
          - parental_level_of_education
          - lunch
          - test_preparation_course

      standardization:
        method: standard_scaler
        with_mean: false
        with_std: true

    y:
      column_math:
        method: mean_of_columns
        output_column: mean_score
        inplace: True
        input_column:
          - math_score
          - reading_score
          - writing_score

      standardization:
        method: standard_scaler
        with_mean: true
        with_std: true

model_trainer:
  models:
    - name: sklearn.ensemble.RandomForestRegressor
      params:
        n_estimators: 100
        max_depth: 10
        random_state: 42
      search_space:
        n_estimators:
          distribution: int
          low: 50
          high: 300
          step: 10
        max_depth:
          distribution: int
          low: 5
          high: 50
          step: 1

    - name: sklearn.ensemble.GradientBoostingRegressor
      params:
        n_estimators: 100
        learning_rate: 0.1
        max_depth: 3
        random_state: 42
      search_space:
        n_estimators:
          distribution: int
          low: 50
          high: 200
          step: 10
        learning_rate:
          distribution: float
          low: 0.01
          high: 1.0
          log: true
        max_depth:
          distribution: int
          low: 2
          high: 10

  optimization:
    enabled: true
    method: optuna
    n_trials: 30
    direction: maximize
    cv_folds: 5
    scoring: neg_root_mean_squared_error

tracking:
  mlflow:
    enabled: true
    experiment_name: StudentPerformanceExperiment
    registry_model_name: StudentPerformanceModel
    metrics_to_log:
      - neg_root_mean_squared_error
      - r2
      - neg_mean_absolute_error
      - neg_mean_squared_error
      - adjusted_r2
    log_trials: false
  
model_evaluation:
  metrics:
    - mean_absolute_error
    - mean_squared_error
    - root_mean_squared_error
    - r2
    - adjusted_r2
    - median_absolute_error
    - explained_variance_score
  
